language: java
jdk: openjdk11
os: 
  - osx
  - linux
git:
  symlinks: true
  
branches:
  only: main
    
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
    
script: gradle clean build test check 
