language: java
jdk: openjdk8
os:
  - linux
  - osx
git:
  symlinks: true
  
branches:
  only: main
    
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
  
jobs:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode9.3
    
script: gradle clean build test check 
