name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest, windows-latest, macos-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi there! This seems to be your first issue here. Thanks for contributing!'
        pr-message: 'Hello! Looks like this is your first Pull Request here. Thank you for contributing to this project!'
