name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: windows-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been here for a long time. Attention needed'
        stale-pr-message: 'This pull request has not been reviewed or merged for a long time. Attention needed'
        stale-issue-label: 'stale-issue'
        stale-pr-label: 'stale-PR'
